services:
  db:
    container_name: db
    image: postgres:15-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=knh
      - POSTGRES_PASSWORD=knh1!
      - POSTGRES_DB=knh
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-postgres

  backend:
    build: backend
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres

networks:
  spring-postgres:      